#![allow(unused)]
#![allow(nonstandard_style)]
// THIS FILE WAS AUTOGENERATED USING A SCRIPT.
// Any changes made here can be lost! Please view ./spec/stir.pl to make changes.


// This file defines the ISA for Stir.


// Common imports needed by all ISAs:
use crate::traits::InstructionTrait;
use crate::builder::BBID;
use IRInstr::*;

// Extra imports:
use crate::isa::*;

#[derive(Debug, Clone)]
pub enum IRInstr {
    Add(IRType, IRValue, IRValue, IRValue),
    Alloca(IRType, IRValue),
    Br(IRValue, BBID, BBID),
    Comment(String),
    Copy(IRType, IRValue, IRValue),
    Getaddr(IRValue, IRValue, IRType, IRValue),
    Icmp(Cmp, IRType, IRValue, IRValue, IRValue),
    Jmp(BBID),
    Load(IRType, IRValue, IRValue),
    Ret(IRType, IRValue),
    Retv,
    Sdiv(IRType, IRValue, IRValue, IRValue),
    Sext(IRType, IRValue, IRType, IRValue),
    Smul(IRType, IRValue, IRValue, IRValue),
    Store(IRType, IRValue, IRValue),
    Sub(IRType, IRValue, IRValue, IRValue),
    Trunc(IRType, IRValue, IRType, IRValue),
    Udiv(IRType, IRValue, IRValue, IRValue),
    Umul(IRType, IRValue, IRValue, IRValue),
    Zext(IRType, IRValue, IRType, IRValue),
}

impl std::fmt::Display for IRInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Add(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = add {ty}, {lhs}, {rhs}")),
            Alloca(ty, dst) => f.write_fmt(format_args!("{dst} = alloca {ty}")),
            Br(val, truebb, falsebb) => f.write_fmt(format_args!("br {val}, {truebb}, {falsebb}")),
            Comment(s) => f.write_fmt(format_args!("; {s}")),
            Copy(ty, dst, rs1) => f.write_fmt(format_args!("{dst} = copy {ty}, {rs1}")),
            Getaddr(dst, base, elem_ty, idx) => f.write_fmt(format_args!("{dst} = getaddr {base} offset by {elem_ty}, {idx}")),
            Icmp(cmp, ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = icmp {cmp} {ty}, {lhs}, {rhs}")),
            Jmp(to) => f.write_fmt(format_args!("jmp {to}")),
            Load(ty, ptr, dst) => f.write_fmt(format_args!("{dst} = load {ty} from {ptr}")),
            Ret(ty, val) => f.write_fmt(format_args!("ret {ty}, {val}")),
            Retv => f.write_fmt(format_args!("retv")),
            Sdiv(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = sdiv {ty}, {lhs}, {rhs}")),
            Sext(to_ty, dst, from_ty, rs1) => f.write_fmt(format_args!("{dst} = sext {from_ty} {rs1} to {to_ty}")),
            Smul(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = smul {ty}, {lhs}, {rhs}")),
            Store(ty, ptr, rs1) => f.write_fmt(format_args!("store {ty} {rs1} into {ptr}")),
            Sub(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = sub {ty}, {lhs}, {rhs}")),
            Trunc(to_ty, dst, from_ty, rs1) => f.write_fmt(format_args!("{dst} = trunc {from_ty} {rs1} to {to_ty}")),
            Udiv(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = udiv {ty}, {lhs}, {rhs}")),
            Umul(ty, dst, lhs, rhs) => f.write_fmt(format_args!("{dst} = umul {ty}, {lhs}, {rhs}")),
            Zext(to_ty, dst, from_ty, rs1) => f.write_fmt(format_args!("{dst} = zext {from_ty} {rs1} to {to_ty}")),
        }
    }
}

impl InstructionTrait for IRInstr {
    type Val = IRValue;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Alloca(ty, dst) => vec![].into_iter(),
            Br(val, truebb, falsebb) => vec![val].into_iter(),
            Comment(s) => vec![].into_iter(),
            Copy(ty, dst, rs1) => vec![rs1].into_iter(),
            Getaddr(dst, base, elem_ty, idx) => vec![base, idx].into_iter(),
            Icmp(cmp, ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Load(ty, ptr, dst) => vec![ptr].into_iter(),
            Ret(ty, val) => vec![val].into_iter(),
            Retv => vec![].into_iter(),
            Sdiv(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Sext(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
            Smul(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Store(ty, ptr, rs1) => vec![ptr, rs1].into_iter(),
            Sub(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Trunc(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
            Udiv(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Umul(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Zext(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Alloca(ty, dst) => vec![].into_iter(),
            Br(val, truebb, falsebb) => vec![val].into_iter(),
            Comment(s) => vec![].into_iter(),
            Copy(ty, dst, rs1) => vec![rs1].into_iter(),
            Getaddr(dst, base, elem_ty, idx) => vec![base, idx].into_iter(),
            Icmp(cmp, ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Load(ty, ptr, dst) => vec![ptr].into_iter(),
            Ret(ty, val) => vec![val].into_iter(),
            Retv => vec![].into_iter(),
            Sdiv(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Sext(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
            Smul(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Store(ty, ptr, rs1) => vec![ptr, rs1].into_iter(),
            Sub(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Trunc(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
            Udiv(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Umul(ty, dst, lhs, rhs) => vec![lhs, rhs].into_iter(),
            Zext(to_ty, dst, from_ty, rs1) => vec![rs1].into_iter(),
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
            Add(ty, dst, lhs, rhs) => false,
            Alloca(ty, dst) => false,
            Br(val, truebb, falsebb) => true,
            Comment(s) => false,
            Copy(ty, dst, rs1) => false,
            Getaddr(dst, base, elem_ty, idx) => false,
            Icmp(cmp, ty, dst, lhs, rhs) => false,
            Jmp(to) => true,
            Load(ty, ptr, dst) => false,
            Ret(ty, val) => true,
            Retv => true,
            Sdiv(ty, dst, lhs, rhs) => false,
            Sext(to_ty, dst, from_ty, rs1) => false,
            Smul(ty, dst, lhs, rhs) => false,
            Store(ty, ptr, rs1) => false,
            Sub(ty, dst, lhs, rhs) => false,
            Trunc(to_ty, dst, from_ty, rs1) => false,
            Udiv(ty, dst, lhs, rhs) => false,
            Umul(ty, dst, lhs, rhs) => false,
            Zext(to_ty, dst, from_ty, rs1) => false,
        }
    }
}

