#![allow(unused)]
#![allow(nonstandard_style)]
// THIS FILE WAS AUTOGENERATED USING A SCRIPT.
// ANY CHANGES MADE HERE WILL BE LOST. 
// Please make changes to ./srcgen//x86.pl instead.


// This file defines the ISA for x86.


// Common imports needed by all ISAs:
use crate::common::traits::InstructionTrait;
use x86Instr::*;

// Extra imports:
use crate::targets::x86::isa::*;
use crate::targets::x86::builder::*;

#[derive(Debug, Clone)]
pub enum x86Instr {
    /// rs1, rs2
    Add(x86Value, x86Value),
    /// dst, rs1
    Cmove(x86Value, x86Value),
    /// dst, rs1
    Cmovg(x86Value, x86Value),
    /// dst, rs1
    Cmovge(x86Value, x86Value),
    /// dst, rs1
    Cmovl(x86Value, x86Value),
    /// dst, rs1
    Cmovle(x86Value, x86Value),
    /// dst, rs1
    Cmovne(x86Value, x86Value),
    /// rs1, rs2
    Cmp(x86Value, x86Value),
    /// s
    Comment(String),
    /// rs1, rs2
    Idiv(x86Value, x86Value),
    /// rs1, rs2
    Imul(x86Value, x86Value),
    /// to
    Je(x86BB),
    /// to
    Jg(x86BB),
    /// to
    Jge(x86BB),
    /// to
    Jl(x86BB),
    /// to
    Jle(x86BB),
    /// to
    Jmp(x86BB),
    /// to
    Jne(x86BB),
    /// to
    Jno(x86BB),
    /// to
    Jnz(x86BB),
    /// to
    Jo(x86BB),
    /// to
    Jz(x86BB),
    /// dst, rs1
    Lea(x86Value, x86Value),
    /// dst, rs1
    Mov(x86Value, x86Value),
    /// dst, rs1
    Movsx(x86Value, x86Value),
    /// dst, rs1
    Movsxd(x86Value, x86Value),
    /// dst, rs1
    Movzx(x86Value, x86Value),
    /// dst
    Pop(x86Value),
    /// rs1
    Push(x86Value),
    /// 
    Ret,
    /// rs1, rs2
    Sub(x86Value, x86Value),
}

impl std::fmt::Display for x86Instr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Add(rs1, rs2) => f.write_fmt(format_args!("add {rs1}, {rs2}")),
            Cmove(dst, rs1) => f.write_fmt(format_args!("cmove {dst}, {rs1}")),
            Cmovg(dst, rs1) => f.write_fmt(format_args!("cmovg {dst}, {rs1}")),
            Cmovge(dst, rs1) => f.write_fmt(format_args!("cmovge {dst}, {rs1}")),
            Cmovl(dst, rs1) => f.write_fmt(format_args!("cmovl {dst}, {rs1}")),
            Cmovle(dst, rs1) => f.write_fmt(format_args!("cmovle {dst}, {rs1}")),
            Cmovne(dst, rs1) => f.write_fmt(format_args!("cmovne {dst}, {rs1}")),
            Cmp(rs1, rs2) => f.write_fmt(format_args!("cmp {rs1}, {rs2}")),
            Comment(s) => f.write_fmt(format_args!("; {s}")),
            Idiv(rs1, rs2) => f.write_fmt(format_args!("idiv {rs1}, {rs2}")),
            Imul(rs1, rs2) => f.write_fmt(format_args!("imul {rs1}, {rs2}")),
            Je(to) => f.write_fmt(format_args!("je {to}")),
            Jg(to) => f.write_fmt(format_args!("jg {to}")),
            Jge(to) => f.write_fmt(format_args!("jge {to}")),
            Jl(to) => f.write_fmt(format_args!("jl {to}")),
            Jle(to) => f.write_fmt(format_args!("jle {to}")),
            Jmp(to) => f.write_fmt(format_args!("jmp {to}")),
            Jne(to) => f.write_fmt(format_args!("jne {to}")),
            Jno(to) => f.write_fmt(format_args!("jno {to}")),
            Jnz(to) => f.write_fmt(format_args!("jnz {to}")),
            Jo(to) => f.write_fmt(format_args!("jo {to}")),
            Jz(to) => f.write_fmt(format_args!("jz {to}")),
            Lea(dst, rs1) => f.write_fmt(format_args!("lea {dst}, {rs1}")),
            Mov(dst, rs1) => f.write_fmt(format_args!("mov {dst}, {rs1}")),
            Movsx(dst, rs1) => f.write_fmt(format_args!("movsx {dst}, {rs1}")),
            Movsxd(dst, rs1) => f.write_fmt(format_args!("movsxd {dst}, {rs1}")),
            Movzx(dst, rs1) => f.write_fmt(format_args!("movzx {dst}, {rs1}")),
            Pop(dst) => f.write_fmt(format_args!("pop {dst}")),
            Push(rs1) => f.write_fmt(format_args!("push {rs1}")),
            Ret => f.write_fmt(format_args!("ret")),
            Sub(rs1, rs2) => f.write_fmt(format_args!("sub {rs1}, {rs2}")),
        }
    }
}

impl InstructionTrait for x86Instr {
    type Val = x86Value;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Cmove(dst, rs1) => vec![rs1].into_iter(),
            Cmovg(dst, rs1) => vec![rs1].into_iter(),
            Cmovge(dst, rs1) => vec![rs1].into_iter(),
            Cmovl(dst, rs1) => vec![rs1].into_iter(),
            Cmovle(dst, rs1) => vec![rs1].into_iter(),
            Cmovne(dst, rs1) => vec![rs1].into_iter(),
            Cmp(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Comment(s) => vec![].into_iter(),
            Idiv(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Imul(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Je(to) => vec![].into_iter(),
            Jg(to) => vec![].into_iter(),
            Jge(to) => vec![].into_iter(),
            Jl(to) => vec![].into_iter(),
            Jle(to) => vec![].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Jne(to) => vec![].into_iter(),
            Jno(to) => vec![].into_iter(),
            Jnz(to) => vec![].into_iter(),
            Jo(to) => vec![].into_iter(),
            Jz(to) => vec![].into_iter(),
            Lea(dst, rs1) => vec![rs1].into_iter(),
            Mov(dst, rs1) => vec![rs1].into_iter(),
            Movsx(dst, rs1) => vec![rs1].into_iter(),
            Movsxd(dst, rs1) => vec![rs1].into_iter(),
            Movzx(dst, rs1) => vec![rs1].into_iter(),
            Pop(dst) => vec![].into_iter(),
            Push(rs1) => vec![rs1].into_iter(),
            Ret => vec![].into_iter(),
            Sub(rs1, rs2) => vec![rs1, rs2].into_iter(),
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1].into_iter(),
            Cmove(dst, rs1) => vec![dst].into_iter(),
            Cmovg(dst, rs1) => vec![dst].into_iter(),
            Cmovge(dst, rs1) => vec![dst].into_iter(),
            Cmovl(dst, rs1) => vec![dst].into_iter(),
            Cmovle(dst, rs1) => vec![dst].into_iter(),
            Cmovne(dst, rs1) => vec![dst].into_iter(),
            Cmp(rs1, rs2) => vec![].into_iter(),
            Comment(s) => vec![].into_iter(),
            Idiv(rs1, rs2) => vec![rs1].into_iter(),
            Imul(rs1, rs2) => vec![rs1].into_iter(),
            Je(to) => vec![].into_iter(),
            Jg(to) => vec![].into_iter(),
            Jge(to) => vec![].into_iter(),
            Jl(to) => vec![].into_iter(),
            Jle(to) => vec![].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Jne(to) => vec![].into_iter(),
            Jno(to) => vec![].into_iter(),
            Jnz(to) => vec![].into_iter(),
            Jo(to) => vec![].into_iter(),
            Jz(to) => vec![].into_iter(),
            Lea(dst, rs1) => vec![dst].into_iter(),
            Mov(dst, rs1) => vec![dst].into_iter(),
            Movsx(dst, rs1) => vec![dst].into_iter(),
            Movsxd(dst, rs1) => vec![dst].into_iter(),
            Movzx(dst, rs1) => vec![dst].into_iter(),
            Pop(dst) => vec![dst].into_iter(),
            Push(rs1) => vec![].into_iter(),
            Ret => vec![].into_iter(),
            Sub(rs1, rs2) => vec![rs1].into_iter(),
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
            Add(rs1, rs2) => false,
            Cmove(dst, rs1) => false,
            Cmovg(dst, rs1) => false,
            Cmovge(dst, rs1) => false,
            Cmovl(dst, rs1) => false,
            Cmovle(dst, rs1) => false,
            Cmovne(dst, rs1) => false,
            Cmp(rs1, rs2) => false,
            Comment(s) => false,
            Idiv(rs1, rs2) => false,
            Imul(rs1, rs2) => false,
            Je(to) => true,
            Jg(to) => true,
            Jge(to) => true,
            Jl(to) => true,
            Jle(to) => true,
            Jmp(to) => true,
            Jne(to) => true,
            Jno(to) => true,
            Jnz(to) => true,
            Jo(to) => true,
            Jz(to) => true,
            Lea(dst, rs1) => false,
            Mov(dst, rs1) => false,
            Movsx(dst, rs1) => false,
            Movsxd(dst, rs1) => false,
            Movzx(dst, rs1) => false,
            Pop(dst) => false,
            Push(rs1) => false,
            Ret => true,
            Sub(rs1, rs2) => false,
        }
    }
}

