#![allow(unused)]
///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/x86/instructions.py
///

use crate::common::*;
use crate::ast::*;
use crate::IRs::lir::*;
use crate::backend::x86::*;

#[derive(Debug, Clone)]
pub enum x86Instr {
		Add(x86Val, x86Val),
		Sub(x86Val, x86Val),
		Mul(x86Val, x86Val),
		Imul(x86Val, x86Val),
		Div(x86Val, x86Val),
		Idiv(x86Val, x86Val),
		And(x86Val, x86Val),
		Or(x86Val, x86Val),
		Xor(x86Val, x86Val),
		Shl(x86Val, x86Val),
		Shr(x86Val, x86Val),
		Sal(x86Val, x86Val),
		Sar(x86Val, x86Val),
		Lea(x86Val, x86Val),
		Mov(x86Val, x86Val),
		Movzx(x86Val, x86Val),
		Movsx(x86Val, x86Val),
		Movsxd(x86Val, x86Val),
		Cmove(x86Val, x86Val),
		Cmovne(x86Val, x86Val),
		Cmovl(x86Val, x86Val),
		Cmovle(x86Val, x86Val),
		Cmovg(x86Val, x86Val),
		Cmovge(x86Val, x86Val),
		Cmp(x86Val, x86Val),
		Comment(String),
		Push(x86Val),
		Pop(x86Val),
		Call(x86Val),
		Ret,
		Jmp(BBID),
		Je(BBID),
		Jne(BBID),
		Jl(BBID),
		Jle(BBID),
		Jg(BBID),
		Jge(BBID),
		Jo(BBID),
		Jno(BBID),
		Jz(BBID),
		Jnz(BBID),
}


impl std::fmt::Display for x86Instr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
						Self::Add(v0, v1) => f.write_fmt(format_args!("add {v0}, {v1}")),
						Self::Sub(v0, v1) => f.write_fmt(format_args!("sub {v0}, {v1}")),
						Self::Mul(v0, v1) => f.write_fmt(format_args!("mul {v1}")),
						Self::Imul(v0, v1) => f.write_fmt(format_args!("imul {v0}, {v1}")),
						Self::Div(v0, v1) => f.write_fmt(format_args!("div {v0}, {v1}")),
						Self::Idiv(v0, v1) => f.write_fmt(format_args!("idiv {v0}, {v1}")),
						Self::And(v0, v1) => f.write_fmt(format_args!("and {v0}, {v1}")),
						Self::Or(v0, v1) => f.write_fmt(format_args!("or {v0}, {v1}")),
						Self::Xor(v0, v1) => f.write_fmt(format_args!("xor {v0}, {v1}")),
						Self::Shl(v0, v1) => f.write_fmt(format_args!("shl {v0}, {v1}")),
						Self::Shr(v0, v1) => f.write_fmt(format_args!("shr {v0}, {v1}")),
						Self::Sal(v0, v1) => f.write_fmt(format_args!("sal {v0}, {v1}")),
						Self::Sar(v0, v1) => f.write_fmt(format_args!("sar {v0}, {v1}")),
						Self::Lea(v0, v1) => f.write_fmt(format_args!("lea {v0}, {v1}")),
						Self::Mov(v0, v1) => f.write_fmt(format_args!("mov {v0}, {v1}")),
						Self::Movzx(v0, v1) => f.write_fmt(format_args!("movzx {v0}, {v1}")),
						Self::Movsx(v0, v1) => f.write_fmt(format_args!("movsx {v0}, {v1}")),
						Self::Movsxd(v0, v1) => f.write_fmt(format_args!("movsxd {v0}, {v1}")),
						Self::Cmove(v0, v1) => f.write_fmt(format_args!("cmove {v0}, {v1}")),
						Self::Cmovne(v0, v1) => f.write_fmt(format_args!("cmovne {v0}, {v1}")),
						Self::Cmovl(v0, v1) => f.write_fmt(format_args!("cmovl {v0}, {v1}")),
						Self::Cmovle(v0, v1) => f.write_fmt(format_args!("cmovle {v0}, {v1}")),
						Self::Cmovg(v0, v1) => f.write_fmt(format_args!("cmovg {v0}, {v1}")),
						Self::Cmovge(v0, v1) => f.write_fmt(format_args!("cmovge {v0}, {v1}")),
						Self::Cmp(v0, v1) => f.write_fmt(format_args!("cmp {v0}, {v1}")),
						Self::Comment(v0) => f.write_fmt(format_args!("; {v0}")),
						Self::Push(v0) => f.write_fmt(format_args!("push {v0}")),
						Self::Pop(v0) => f.write_fmt(format_args!("pop {v0}")),
						Self::Call(v0) => f.write_fmt(format_args!("call {v0}")),
						Self::Ret => f.write_fmt(format_args!("ret")),
						Self::Jmp(v0) => f.write_fmt(format_args!("jmp {v0}")),
						Self::Je(v0) => f.write_fmt(format_args!("je {v0}")),
						Self::Jne(v0) => f.write_fmt(format_args!("jne {v0}")),
						Self::Jl(v0) => f.write_fmt(format_args!("jl {v0}")),
						Self::Jle(v0) => f.write_fmt(format_args!("jle {v0}")),
						Self::Jg(v0) => f.write_fmt(format_args!("jg {v0}")),
						Self::Jge(v0) => f.write_fmt(format_args!("jge {v0}")),
						Self::Jo(v0) => f.write_fmt(format_args!("jo {v0}")),
						Self::Jno(v0) => f.write_fmt(format_args!("jno {v0}")),
						Self::Jz(v0) => f.write_fmt(format_args!("jz {v0}")),
						Self::Jnz(v0) => f.write_fmt(format_args!("jnz {v0}"))
        }
    }
}
        


impl Instr for x86Instr {
    type Val = x86Val;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1) => vec![v0, v1].into_iter(),
						Self::Sub(v0, v1) => vec![v0, v1].into_iter(),
						Self::Mul(v0, v1) => vec![v0, v1].into_iter(),
						Self::Imul(v0, v1) => vec![v0, v1].into_iter(),
						Self::Div(v0, v1) => vec![v0, v1].into_iter(),
						Self::Idiv(v0, v1) => vec![v0, v1].into_iter(),
						Self::And(v0, v1) => vec![v0, v1].into_iter(),
						Self::Or(v0, v1) => vec![v0, v1].into_iter(),
						Self::Xor(v0, v1) => vec![v0, v1].into_iter(),
						Self::Shl(v0, v1) => vec![v0, v1].into_iter(),
						Self::Shr(v0, v1) => vec![v0, v1].into_iter(),
						Self::Sal(v0, v1) => vec![v0, v1].into_iter(),
						Self::Sar(v0, v1) => vec![v0, v1].into_iter(),
						Self::Lea(v0, v1) => vec![v0, v1].into_iter(),
						Self::Mov(v0, v1) => vec![v1].into_iter(),
						Self::Movzx(v0, v1) => vec![v1].into_iter(),
						Self::Movsx(v0, v1) => vec![v1].into_iter(),
						Self::Movsxd(v0, v1) => vec![v1].into_iter(),
						Self::Cmove(v0, v1) => vec![v1].into_iter(),
						Self::Cmovne(v0, v1) => vec![v1].into_iter(),
						Self::Cmovl(v0, v1) => vec![v1].into_iter(),
						Self::Cmovle(v0, v1) => vec![v1].into_iter(),
						Self::Cmovg(v0, v1) => vec![v1].into_iter(),
						Self::Cmovge(v0, v1) => vec![v1].into_iter(),
						Self::Cmp(v0, v1) => vec![v0, v1].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Push(v0) => vec![v0].into_iter(),
						Self::Pop(v0) => vec![].into_iter(),
						Self::Call(v0) => vec![v0].into_iter(),
						Self::Ret => vec![].into_iter(),
						Self::Jmp(v0) => vec![].into_iter(),
						Self::Je(v0) => vec![].into_iter(),
						Self::Jne(v0) => vec![].into_iter(),
						Self::Jl(v0) => vec![].into_iter(),
						Self::Jle(v0) => vec![].into_iter(),
						Self::Jg(v0) => vec![].into_iter(),
						Self::Jge(v0) => vec![].into_iter(),
						Self::Jo(v0) => vec![].into_iter(),
						Self::Jno(v0) => vec![].into_iter(),
						Self::Jz(v0) => vec![].into_iter(),
						Self::Jnz(v0) => vec![].into_iter()
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1) => vec![v0].into_iter(),
						Self::Sub(v0, v1) => vec![v0].into_iter(),
						Self::Mul(v0, v1) => vec![v0].into_iter(),
						Self::Imul(v0, v1) => vec![v0].into_iter(),
						Self::Div(v0, v1) => vec![v0].into_iter(),
						Self::Idiv(v0, v1) => vec![v0].into_iter(),
						Self::And(v0, v1) => vec![v0].into_iter(),
						Self::Or(v0, v1) => vec![v0].into_iter(),
						Self::Xor(v0, v1) => vec![v0].into_iter(),
						Self::Shl(v0, v1) => vec![v0].into_iter(),
						Self::Shr(v0, v1) => vec![v0].into_iter(),
						Self::Sal(v0, v1) => vec![v0].into_iter(),
						Self::Sar(v0, v1) => vec![v0].into_iter(),
						Self::Lea(v0, v1) => vec![v0].into_iter(),
						Self::Mov(v0, v1) => vec![v0].into_iter(),
						Self::Movzx(v0, v1) => vec![v0].into_iter(),
						Self::Movsx(v0, v1) => vec![v0].into_iter(),
						Self::Movsxd(v0, v1) => vec![v0].into_iter(),
						Self::Cmove(v0, v1) => vec![v0].into_iter(),
						Self::Cmovne(v0, v1) => vec![v0].into_iter(),
						Self::Cmovl(v0, v1) => vec![v0].into_iter(),
						Self::Cmovle(v0, v1) => vec![v0].into_iter(),
						Self::Cmovg(v0, v1) => vec![v0].into_iter(),
						Self::Cmovge(v0, v1) => vec![v0].into_iter(),
						Self::Cmp(v0, v1) => vec![].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Push(v0) => vec![].into_iter(),
						Self::Pop(v0) => vec![v0].into_iter(),
						Self::Call(v0) => vec![].into_iter(),
						Self::Ret => vec![].into_iter(),
						Self::Jmp(v0) => vec![].into_iter(),
						Self::Je(v0) => vec![].into_iter(),
						Self::Jne(v0) => vec![].into_iter(),
						Self::Jl(v0) => vec![].into_iter(),
						Self::Jle(v0) => vec![].into_iter(),
						Self::Jg(v0) => vec![].into_iter(),
						Self::Jge(v0) => vec![].into_iter(),
						Self::Jo(v0) => vec![].into_iter(),
						Self::Jno(v0) => vec![].into_iter(),
						Self::Jz(v0) => vec![].into_iter(),
						Self::Jnz(v0) => vec![].into_iter()
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
						Self::Add(v0, v1) => false,
						Self::Sub(v0, v1) => false,
						Self::Mul(v0, v1) => false,
						Self::Imul(v0, v1) => false,
						Self::Div(v0, v1) => false,
						Self::Idiv(v0, v1) => false,
						Self::And(v0, v1) => false,
						Self::Or(v0, v1) => false,
						Self::Xor(v0, v1) => false,
						Self::Shl(v0, v1) => false,
						Self::Shr(v0, v1) => false,
						Self::Sal(v0, v1) => false,
						Self::Sar(v0, v1) => false,
						Self::Lea(v0, v1) => false,
						Self::Mov(v0, v1) => false,
						Self::Movzx(v0, v1) => false,
						Self::Movsx(v0, v1) => false,
						Self::Movsxd(v0, v1) => false,
						Self::Cmove(v0, v1) => false,
						Self::Cmovne(v0, v1) => false,
						Self::Cmovl(v0, v1) => false,
						Self::Cmovle(v0, v1) => false,
						Self::Cmovg(v0, v1) => false,
						Self::Cmovge(v0, v1) => false,
						Self::Cmp(v0, v1) => false,
						Self::Comment(v0) => false,
						Self::Push(v0) => false,
						Self::Pop(v0) => false,
						Self::Call(v0) => false,
						Self::Ret => true,
						Self::Jmp(v0) => true,
						Self::Je(v0) => true,
						Self::Jne(v0) => true,
						Self::Jl(v0) => true,
						Self::Jle(v0) => true,
						Self::Jg(v0) => true,
						Self::Jge(v0) => true,
						Self::Jo(v0) => true,
						Self::Jno(v0) => true,
						Self::Jz(v0) => true,
						Self::Jnz(v0) => true
        }
    }

    fn uncond_jump(bb: BBID) -> Self {
        Self::Jmp(bb)
    }
}
