use strict;

sub println {
  print @_, "\n"
}

# \t = 4 spaces
my $TAB = "    ";

sub getArgNames {
  my ($args) = @_;

  return map {
      my ($name) = /^([^:]+):/;
      $name;
  } @$args;
}

sub getArgTypes {
  my ($args) = @_;

  return map {
      my ($type) = /:([^:]+)$/;
      $type;
  } @$args;
}

sub namedArmBase {
  my ($op, $instr) = @_;

  my @arg_names = getArgNames($instr->{args});

  my $op_uc = ucfirst $op;

  return "$op_uc" unless @arg_names;

  my $args_str = join(", ", @arg_names);
  return "$op_uc($args_str)";
}

sub typedArmBase {
  my ($op, $instr) = @_;

  my @arg_types = getArgTypes($instr->{args});

  my $op_uc = ucfirst $op;
  return $op_uc unless @arg_types;

  my $args_str = join(", ", @arg_types);
  return "$op_uc($args_str)";
}

sub createFmtArm {
  my ($op, $instr) = @_;

  my $base = namedArmBase($op, $instr);
  
  my $fmt = $instr->{fmt};
  $fmt =~ s/{name}/$op/g;

  return "$base => f.write_fmt(format_args!(\"$fmt\")),"
}

sub printEnum {
  my ($isa) = @_;

  my %instructions = %{$isa->{instructions}};
  my $arms = "";
  foreach my $op (sort keys %instructions) {
    my $instr = $instructions{$op};
    $arms .= "$TAB";
    $arms .= "/// ";
    $arms .= join(", ", getArgNames($instr->{args}));
    $arms .= "\n";
    $arms .= "$TAB";
    $arms .=  typedArmBase($op, $instr);
    $arms .= ",\n";
  }
  $arms =~ s/\n$//; # strip last newline
  println <<END;
#[derive(Debug, Clone)]
pub enum $isa->{instrName} {
$arms
}
END
}

sub printDisplayImpl {
  my ($isa) = @_;

  my %instructions = %{$isa->{instructions}};
  my $arms = "";
  foreach my $op (sort keys %instructions) {
    my $instr = $instructions{$op};
    $arms .= "$TAB$TAB$TAB";
    $arms .= createFmtArm($op, $instr);
    $arms .= "\n";
  }
  $arms =~ s/\n$//; # strip last newline
  println <<END;
impl std::fmt::Display for $isa->{instrName} {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
$arms
        }
    }
}
END
}

sub printInstructionTraitImpl {
  my ($isa) = @_;

  my %instructions = %{$isa->{instructions}};
  my $srcs_arms = "";
  my $dsts_arms = "";
  my $term_arms = "";
  foreach my $op (sort keys %instructions) {
    my $instr = $instructions{$op};
    my $srcs = join(", ", @{$instr->{uses}});
    my $dsts = join(", ", @{$instr->{defs}});
    my $isTerm = "false";
    if ($instr->{term}) {
      $isTerm = "true"
    }
    $srcs_arms .= ("$TAB$TAB$TAB" . namedArmBase($op, $instr) . " => vec![$srcs].into_iter()" . ",\n");
    $dsts_arms .= ("$TAB$TAB$TAB" . namedArmBase($op, $instr) . " => vec![$dsts].into_iter()" . ",\n");
    $term_arms .= ("$TAB$TAB$TAB" . namedArmBase($op, $instr) . " => $isTerm" . ",\n");
  }
  $srcs_arms =~ s/\n$//; # strip last newline
  $dsts_arms =~ s/\n$//; # strip last newline
  $term_arms =~ s/\n$//; # strip last newline

println <<END;
impl InstructionTrait for $isa->{instrName} {
    type Val = $isa->{value};

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
$srcs_arms
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
$dsts_arms
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
$term_arms
        }
    }
}
END
}

sub validateIsa {
  my ($isa) = @_;

  for my $op (sort keys %{ $isa->{instructions} }) {
      my $instr = $isa->{instructions}{$op};

      $instr->{args} //= [];
      $instr->{uses} //= [];
      $instr->{defs} //= [];

      foreach my $arg (@{ $instr->{args} }) {
        if ($arg !~ /^([^:]+):([^:]+)$/) {
          die "Argument $arg does not match `NAME:TY` format"
        }
      }

      my @arg_names = map {
          my ($name) = /^([^:]+):/;
          "{$name}";
      } @{ $instr->{args} };

      my $fmt_args = @arg_names ? " " . join(", ", @arg_names) : "";

      $instr->{fmt}  //= ($op . $fmt_args);
      $instr->{term} //= 0;
  }
}


sub printAll {
  my ($isa) = @_;
  validateIsa($isa);

  print <<END;
#![allow(unused)]
#![allow(nonstandard_style)]
// THIS FILE WAS AUTOGENERATED USING A SCRIPT.
// ANY CHANGES MADE HERE WILL BE LOST. 
// Please make changes to $isa->{specFile} instead.


// This file defines the ISA for $isa->{isaName}.


// Common imports needed by all ISAs:
use crate::common::traits::InstructionTrait;
use $isa->{instrName}::*;

// Extra imports:
END

  foreach my $line (@{$isa->{extraCode}}) {
    println $line;
  }

  println "";
  printEnum($isa);
  printDisplayImpl($isa);
  printInstructionTraitImpl($isa);
}

1;
