#![allow(unused)]
///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/lir/instructions.py
///

use crate::common::*;
use crate::ast::*;
use crate::backend::*;
use crate::IRs::lir::*;

#[derive(Debug, Clone)]
pub enum LirInstr {
		Add(TypeId, Value, Value, Value),
		Sub(TypeId, Value, Value, Value),
		Umul(TypeId, Value, Value, Value),
		Smul(TypeId, Value, Value, Value),
		Udiv(TypeId, Value, Value, Value),
		Sdiv(TypeId, Value, Value, Value),
		Eq(TypeId, Value, Value, Value),
		Sgt(TypeId, Value, Value, Value),
		Sge(TypeId, Value, Value, Value),
		Slt(TypeId, Value, Value, Value),
		Sle(TypeId, Value, Value, Value),
		Ugt(TypeId, Value, Value, Value),
		Uge(TypeId, Value, Value, Value),
		Ult(TypeId, Value, Value, Value),
		Ule(TypeId, Value, Value, Value),
		Comment(String),
		Call(Value),
		Copy(Value, Value),
		Load(TypeId, Value, Value),
		Store(TypeId, Value, Value),
		Alloca(TypeId, Value),
		Sext(TypeId, Value, Value),
		Zext(TypeId, Value, Value),
		Trunc(TypeId, Value, Value),
		Retv,
		Ret(TypeId, Value),
		Br(Value, BBID, BBID),
		Jmp(BBID),
}


impl std::fmt::Display for LirInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
						Self::Add(v0, v1, v2, v3) => f.write_fmt(format_args!("add {v0}, {v1}, {v2}, {v3}")),
						Self::Sub(v0, v1, v2, v3) => f.write_fmt(format_args!("sub {v0}, {v1}, {v2}, {v3}")),
						Self::Umul(v0, v1, v2, v3) => f.write_fmt(format_args!("umul {v0}, {v1}, {v2}, {v3}")),
						Self::Smul(v0, v1, v2, v3) => f.write_fmt(format_args!("smul {v0}, {v1}, {v2}, {v3}")),
						Self::Udiv(v0, v1, v2, v3) => f.write_fmt(format_args!("udiv {v0}, {v1}, {v2}, {v3}")),
						Self::Sdiv(v0, v1, v2, v3) => f.write_fmt(format_args!("sdiv {v0}, {v1}, {v2}, {v3}")),
						Self::Eq(v0, v1, v2, v3) => f.write_fmt(format_args!("eq {v0}, {v1}, {v2}, {v3}")),
						Self::Sgt(v0, v1, v2, v3) => f.write_fmt(format_args!("sgt {v0}, {v1}, {v2}, {v3}")),
						Self::Sge(v0, v1, v2, v3) => f.write_fmt(format_args!("sge {v0}, {v1}, {v2}, {v3}")),
						Self::Slt(v0, v1, v2, v3) => f.write_fmt(format_args!("slt {v0}, {v1}, {v2}, {v3}")),
						Self::Sle(v0, v1, v2, v3) => f.write_fmt(format_args!("sle {v0}, {v1}, {v2}, {v3}")),
						Self::Ugt(v0, v1, v2, v3) => f.write_fmt(format_args!("ugt {v0}, {v1}, {v2}, {v3}")),
						Self::Uge(v0, v1, v2, v3) => f.write_fmt(format_args!("uge {v0}, {v1}, {v2}, {v3}")),
						Self::Ult(v0, v1, v2, v3) => f.write_fmt(format_args!("ult {v0}, {v1}, {v2}, {v3}")),
						Self::Ule(v0, v1, v2, v3) => f.write_fmt(format_args!("ule {v0}, {v1}, {v2}, {v3}")),
						Self::Comment(v0) => f.write_fmt(format_args!("; {v0}")),
						Self::Call(v0) => f.write_fmt(format_args!("call {v0}")),
						Self::Copy(v0, v1) => f.write_fmt(format_args!("copy {v0}, {v1}")),
						Self::Load(v0, v1, v2) => f.write_fmt(format_args!("load {v0}, {v1}, {v2}")),
						Self::Store(v0, v1, v2) => f.write_fmt(format_args!("store {v0}, {v1}, {v2}")),
						Self::Alloca(v0, v1) => f.write_fmt(format_args!("alloca {v0}, {v1}")),
						Self::Sext(v0, v1, v2) => f.write_fmt(format_args!("sext {v0}, {v1}, {v2}")),
						Self::Zext(v0, v1, v2) => f.write_fmt(format_args!("zext {v0}, {v1}, {v2}")),
						Self::Trunc(v0, v1, v2) => f.write_fmt(format_args!("trunc {v0}, {v1}, {v2}")),
						Self::Retv => f.write_fmt(format_args!("ret")),
						Self::Ret(v0, v1) => f.write_fmt(format_args!("ret {v0}, {v1}")),
						Self::Br(v0, v1, v2) => f.write_fmt(format_args!("br {v0}, {v1}, {v2}")),
						Self::Jmp(v0) => f.write_fmt(format_args!("jmp {v0}"))
        }
    }
}
        


impl Instr for LirInstr {
    type Val = Value;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sub(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Umul(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Smul(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Udiv(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sdiv(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Eq(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sgt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sge(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Slt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sle(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ugt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Uge(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ult(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ule(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Call(v0) => vec![].into_iter(),
						Self::Copy(v0, v1) => vec![v1].into_iter(),
						Self::Load(v0, v1, v2) => vec![v2].into_iter(),
						Self::Store(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Alloca(v0, v1) => vec![].into_iter(),
						Self::Sext(v0, v1, v2) => vec![v2].into_iter(),
						Self::Zext(v0, v1, v2) => vec![v2].into_iter(),
						Self::Trunc(v0, v1, v2) => vec![v2].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0, v1) => vec![v1].into_iter(),
						Self::Br(v0, v1, v2) => vec![v0].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sub(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Umul(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Smul(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Udiv(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sdiv(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Eq(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sgt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sge(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Slt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sle(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ugt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Uge(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ult(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ule(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Call(v0) => vec![v0].into_iter(),
						Self::Copy(v0, v1) => vec![v0].into_iter(),
						Self::Load(v0, v1, v2) => vec![v1].into_iter(),
						Self::Store(v0, v1, v2) => vec![].into_iter(),
						Self::Alloca(v0, v1) => vec![v1].into_iter(),
						Self::Sext(v0, v1, v2) => vec![v1].into_iter(),
						Self::Zext(v0, v1, v2) => vec![v1].into_iter(),
						Self::Trunc(v0, v1, v2) => vec![v1].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0, v1) => vec![].into_iter(),
						Self::Br(v0, v1, v2) => vec![].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
						Self::Add(v0, v1, v2, v3) => false,
						Self::Sub(v0, v1, v2, v3) => false,
						Self::Umul(v0, v1, v2, v3) => false,
						Self::Smul(v0, v1, v2, v3) => false,
						Self::Udiv(v0, v1, v2, v3) => false,
						Self::Sdiv(v0, v1, v2, v3) => false,
						Self::Eq(v0, v1, v2, v3) => false,
						Self::Sgt(v0, v1, v2, v3) => false,
						Self::Sge(v0, v1, v2, v3) => false,
						Self::Slt(v0, v1, v2, v3) => false,
						Self::Sle(v0, v1, v2, v3) => false,
						Self::Ugt(v0, v1, v2, v3) => false,
						Self::Uge(v0, v1, v2, v3) => false,
						Self::Ult(v0, v1, v2, v3) => false,
						Self::Ule(v0, v1, v2, v3) => false,
						Self::Comment(v0) => false,
						Self::Call(v0) => false,
						Self::Copy(v0, v1) => false,
						Self::Load(v0, v1, v2) => false,
						Self::Store(v0, v1, v2) => false,
						Self::Alloca(v0, v1) => false,
						Self::Sext(v0, v1, v2) => false,
						Self::Zext(v0, v1, v2) => false,
						Self::Trunc(v0, v1, v2) => false,
						Self::Retv => true,
						Self::Ret(v0, v1) => true,
						Self::Br(v0, v1, v2) => true,
						Self::Jmp(v0) => true
        }
    }

    fn uncond_jump(bb: BBID) -> Self {
        Self::Jmp(bb)
    }
}
