///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/lir/instructions.py
///

use crate::prelude::*;
use crate::arch::lir::*;

#[derive(Debug, Clone)]
pub enum LirInstr {
	    Add(LirType, LirVal, LirVal, LirVal),
	    Sub(LirType, LirVal, LirVal, LirVal),
	    Umul(LirType, LirVal, LirVal, LirVal),
	    Smul(LirType, LirVal, LirVal, LirVal),
	    Udiv(LirType, LirVal, LirVal, LirVal),
	    Sdiv(LirType, LirVal, LirVal, LirVal),
	    Eq(LirType, LirVal, LirVal, LirVal),
	    Sgt(LirType, LirVal, LirVal, LirVal),
	    Sge(LirType, LirVal, LirVal, LirVal),
	    Slt(LirType, LirVal, LirVal, LirVal),
	    Sle(LirType, LirVal, LirVal, LirVal),
	    Ugt(LirType, LirVal, LirVal, LirVal),
	    Uge(LirType, LirVal, LirVal, LirVal),
	    Ult(LirType, LirVal, LirVal, LirVal),
	    Ule(LirType, LirVal, LirVal, LirVal),
	    Copyr(LirType, LirVal, LirVal),
	    Alloc(LirType, LirVal, StringId),
	    Param(LirType, LirVal, StringId, usize),
	    Load(LirType, LirVal, LirVal),
	    Store(LirType, LirVal, LirVal),
	    Retv,
	    Ret(LirType, LirVal),
	    Br(LirVal, BB, BB),
	    Jmp(BB),
}


impl std::fmt::Display for LirInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
	    Self::Add(v0, v1, v2, v3) => f.write_fmt(format_args!("add {v0}, {v1}, {v2}, {v3}")),
	    Self::Sub(v0, v1, v2, v3) => f.write_fmt(format_args!("sub {v0}, {v1}, {v2}, {v3}")),
	    Self::Umul(v0, v1, v2, v3) => f.write_fmt(format_args!("umul {v0}, {v1}, {v2}, {v3}")),
	    Self::Smul(v0, v1, v2, v3) => f.write_fmt(format_args!("smul {v0}, {v1}, {v2}, {v3}")),
	    Self::Udiv(v0, v1, v2, v3) => f.write_fmt(format_args!("udiv {v0}, {v1}, {v2}, {v3}")),
	    Self::Sdiv(v0, v1, v2, v3) => f.write_fmt(format_args!("sdiv {v0}, {v1}, {v2}, {v3}")),
	    Self::Eq(v0, v1, v2, v3) => f.write_fmt(format_args!("eq {v0}, {v1}, {v2}, {v3}")),
	    Self::Sgt(v0, v1, v2, v3) => f.write_fmt(format_args!("sgt {v0}, {v1}, {v2}, {v3}")),
	    Self::Sge(v0, v1, v2, v3) => f.write_fmt(format_args!("sge {v0}, {v1}, {v2}, {v3}")),
	    Self::Slt(v0, v1, v2, v3) => f.write_fmt(format_args!("slt {v0}, {v1}, {v2}, {v3}")),
	    Self::Sle(v0, v1, v2, v3) => f.write_fmt(format_args!("sle {v0}, {v1}, {v2}, {v3}")),
	    Self::Ugt(v0, v1, v2, v3) => f.write_fmt(format_args!("ugt {v0}, {v1}, {v2}, {v3}")),
	    Self::Uge(v0, v1, v2, v3) => f.write_fmt(format_args!("uge {v0}, {v1}, {v2}, {v3}")),
	    Self::Ult(v0, v1, v2, v3) => f.write_fmt(format_args!("ult {v0}, {v1}, {v2}, {v3}")),
	    Self::Ule(v0, v1, v2, v3) => f.write_fmt(format_args!("ule {v0}, {v1}, {v2}, {v3}")),
	    Self::Copyr(v0, v1, v2) => f.write_fmt(format_args!("copyr {v0}, {v1}, {v2}")),
	    Self::Alloc(v0, v1, v2) => f.write_fmt(format_args!("alloc {v0}, {v1}, {v2}")),
	    Self::Param(v0, v1, v2, v3) => f.write_fmt(format_args!("param {v0}, {v1}, {v2}, {v3}")),
	    Self::Load(v0, v1, v2) => f.write_fmt(format_args!("load {v0}, {v1}, {v2}")),
	    Self::Store(v0, v1, v2) => f.write_fmt(format_args!("store {v0}, {v1}, {v2}")),
	    Self::Retv => f.write_fmt(format_args!("retv")),
	    Self::Ret(v0, v1) => f.write_fmt(format_args!("ret {v0}, {v1}")),
	    Self::Br(v0, v1, v2) => f.write_fmt(format_args!("br {v0}, {v1}, {v2}")),
	    Self::Jmp(v0) => f.write_fmt(format_args!("jmp {v0}"))
        }
    }
}
        


impl Instr for LirInstr {
    type Val = LirVal;

    fn srcs(&self) -> Vec<&Self::Val> {
        match self {
	    Self::Add(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Sub(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Umul(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Smul(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Udiv(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Sdiv(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Eq(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Sgt(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Sge(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Slt(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Sle(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Ugt(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Uge(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Ult(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Ule(v0, v1, v2, v3) => vec![v2, v3],
	    Self::Copyr(v0, v1, v2) => vec![v2],
	    Self::Alloc(v0, v1, v2) => vec![],
	    Self::Param(v0, v1, v2, v3) => vec![],
	    Self::Load(v0, v1, v2) => vec![v2],
	    Self::Store(v0, v1, v2) => vec![v1, v2],
	    Self::Retv => vec![],
	    Self::Ret(v0, v1) => vec![v1],
	    Self::Br(v0, v1, v2) => vec![v0],
	    Self::Jmp(v0) => vec![]
        }
    }

    fn dsts(&self) -> Vec<&Self::Val> {
        match self {
	    Self::Add(v0, v1, v2, v3) => vec![v1],
	    Self::Sub(v0, v1, v2, v3) => vec![v1],
	    Self::Umul(v0, v1, v2, v3) => vec![v1],
	    Self::Smul(v0, v1, v2, v3) => vec![v1],
	    Self::Udiv(v0, v1, v2, v3) => vec![v1],
	    Self::Sdiv(v0, v1, v2, v3) => vec![v1],
	    Self::Eq(v0, v1, v2, v3) => vec![v1],
	    Self::Sgt(v0, v1, v2, v3) => vec![v1],
	    Self::Sge(v0, v1, v2, v3) => vec![v1],
	    Self::Slt(v0, v1, v2, v3) => vec![v1],
	    Self::Sle(v0, v1, v2, v3) => vec![v1],
	    Self::Ugt(v0, v1, v2, v3) => vec![v1],
	    Self::Uge(v0, v1, v2, v3) => vec![v1],
	    Self::Ult(v0, v1, v2, v3) => vec![v1],
	    Self::Ule(v0, v1, v2, v3) => vec![v1],
	    Self::Copyr(v0, v1, v2) => vec![v1],
	    Self::Alloc(v0, v1, v2) => vec![v1],
	    Self::Param(v0, v1, v2, v3) => vec![v1],
	    Self::Load(v0, v1, v2) => vec![v1],
	    Self::Store(v0, v1, v2) => vec![],
	    Self::Retv => vec![],
	    Self::Ret(v0, v1) => vec![],
	    Self::Br(v0, v1, v2) => vec![],
	    Self::Jmp(v0) => vec![]
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
	    Self::Add(v0, v1, v2, v3) => false,
	    Self::Sub(v0, v1, v2, v3) => false,
	    Self::Umul(v0, v1, v2, v3) => false,
	    Self::Smul(v0, v1, v2, v3) => false,
	    Self::Udiv(v0, v1, v2, v3) => false,
	    Self::Sdiv(v0, v1, v2, v3) => false,
	    Self::Eq(v0, v1, v2, v3) => false,
	    Self::Sgt(v0, v1, v2, v3) => false,
	    Self::Sge(v0, v1, v2, v3) => false,
	    Self::Slt(v0, v1, v2, v3) => false,
	    Self::Sle(v0, v1, v2, v3) => false,
	    Self::Ugt(v0, v1, v2, v3) => false,
	    Self::Uge(v0, v1, v2, v3) => false,
	    Self::Ult(v0, v1, v2, v3) => false,
	    Self::Ule(v0, v1, v2, v3) => false,
	    Self::Copyr(v0, v1, v2) => false,
	    Self::Alloc(v0, v1, v2) => false,
	    Self::Param(v0, v1, v2, v3) => false,
	    Self::Load(v0, v1, v2) => false,
	    Self::Store(v0, v1, v2) => false,
	    Self::Retv => true,
	    Self::Ret(v0, v1) => true,
	    Self::Br(v0, v1, v2) => true,
	    Self::Jmp(v0) => true
        }
    }

    fn uncond_jump(bb: BB) -> Self {
        Self::Jmp(bb)
    }
}
