#![allow(unused)]
///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/lir/instructions.py
///

use crate::prelude::*;
use crate::ast::*;
use crate::arch::lir::*;

#[derive(Debug, Clone)]
pub enum LirInstr {
		Add(TypeId, LirVal, LirVal, LirVal),
		Sub(TypeId, LirVal, LirVal, LirVal),
		Umul(TypeId, LirVal, LirVal, LirVal),
		Smul(TypeId, LirVal, LirVal, LirVal),
		Udiv(TypeId, LirVal, LirVal, LirVal),
		Sdiv(TypeId, LirVal, LirVal, LirVal),
		Eq(TypeId, LirVal, LirVal, LirVal),
		Sgt(TypeId, LirVal, LirVal, LirVal),
		Sge(TypeId, LirVal, LirVal, LirVal),
		Slt(TypeId, LirVal, LirVal, LirVal),
		Sle(TypeId, LirVal, LirVal, LirVal),
		Ugt(TypeId, LirVal, LirVal, LirVal),
		Uge(TypeId, LirVal, LirVal, LirVal),
		Ult(TypeId, LirVal, LirVal, LirVal),
		Ule(TypeId, LirVal, LirVal, LirVal),
		Copy(TypeId, LirVal, LirVal),
		Alloc(TypeId, LirVal, StringId),
		Arg(TypeId, LirVal, StringId, usize),
		Stkarg(TypeId, LirVal, StringId, usize),
		Load(TypeId, LirVal, LirVal),
		Store(TypeId, LirVal, LirVal),
		Comment(String),
		Sext(TypeId, LirVal, LirVal),
		Zext(TypeId, LirVal, LirVal),
		Trunc(TypeId, LirVal, LirVal),
		Retv,
		Ret(TypeId, LirVal),
		Br(TypeId, LirVal, BB, BB),
		Jmp(BB),
}


impl std::fmt::Display for LirInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
						Self::Add(v0, v1, v2, v3) => f.write_fmt(format_args!("add {v0}, {v1}, {v2}, {v3}")),
						Self::Sub(v0, v1, v2, v3) => f.write_fmt(format_args!("sub {v0}, {v1}, {v2}, {v3}")),
						Self::Umul(v0, v1, v2, v3) => f.write_fmt(format_args!("umul {v0}, {v1}, {v2}, {v3}")),
						Self::Smul(v0, v1, v2, v3) => f.write_fmt(format_args!("smul {v0}, {v1}, {v2}, {v3}")),
						Self::Udiv(v0, v1, v2, v3) => f.write_fmt(format_args!("udiv {v0}, {v1}, {v2}, {v3}")),
						Self::Sdiv(v0, v1, v2, v3) => f.write_fmt(format_args!("sdiv {v0}, {v1}, {v2}, {v3}")),
						Self::Eq(v0, v1, v2, v3) => f.write_fmt(format_args!("eq {v0}, {v1}, {v2}, {v3}")),
						Self::Sgt(v0, v1, v2, v3) => f.write_fmt(format_args!("sgt {v0}, {v1}, {v2}, {v3}")),
						Self::Sge(v0, v1, v2, v3) => f.write_fmt(format_args!("sge {v0}, {v1}, {v2}, {v3}")),
						Self::Slt(v0, v1, v2, v3) => f.write_fmt(format_args!("slt {v0}, {v1}, {v2}, {v3}")),
						Self::Sle(v0, v1, v2, v3) => f.write_fmt(format_args!("sle {v0}, {v1}, {v2}, {v3}")),
						Self::Ugt(v0, v1, v2, v3) => f.write_fmt(format_args!("ugt {v0}, {v1}, {v2}, {v3}")),
						Self::Uge(v0, v1, v2, v3) => f.write_fmt(format_args!("uge {v0}, {v1}, {v2}, {v3}")),
						Self::Ult(v0, v1, v2, v3) => f.write_fmt(format_args!("ult {v0}, {v1}, {v2}, {v3}")),
						Self::Ule(v0, v1, v2, v3) => f.write_fmt(format_args!("ule {v0}, {v1}, {v2}, {v3}")),
						Self::Copy(v0, v1, v2) => f.write_fmt(format_args!("copy {v0}, {v1}, {v2}")),
						Self::Alloc(v0, v1, v2) => f.write_fmt(format_args!("alloc {v0}, {v1}, {v2}")),
						Self::Arg(v0, v1, v2, v3) => f.write_fmt(format_args!("arg {v0}, {v1}, {v2}, {v3}")),
						Self::Stkarg(v0, v1, v2, v3) => f.write_fmt(format_args!("stkarg {v0}, {v1}, {v2}, {v3}")),
						Self::Load(v0, v1, v2) => f.write_fmt(format_args!("load {v0}, {v1}, {v2}")),
						Self::Store(v0, v1, v2) => f.write_fmt(format_args!("store {v0}, {v1}, {v2}")),
						Self::Comment(v0) => f.write_fmt(format_args!("; {v0}")),
						Self::Sext(v0, v1, v2) => f.write_fmt(format_args!("sext {v0}, {v1}, {v2}")),
						Self::Zext(v0, v1, v2) => f.write_fmt(format_args!("zext {v0}, {v1}, {v2}")),
						Self::Trunc(v0, v1, v2) => f.write_fmt(format_args!("trunc {v0}, {v1}, {v2}")),
						Self::Retv => f.write_fmt(format_args!("retv")),
						Self::Ret(v0, v1) => f.write_fmt(format_args!("ret {v0}, {v1}")),
						Self::Br(v0, v1, v2, v3) => f.write_fmt(format_args!("br {v0}, {v1}, {v2}, {v3}")),
						Self::Jmp(v0) => f.write_fmt(format_args!("jmp {v0}"))
        }
    }
}
        


impl Instr for LirInstr {
    type Val = LirVal;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sub(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Umul(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Smul(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Udiv(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sdiv(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Eq(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sgt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sge(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Slt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Sle(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ugt(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Uge(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ult(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Ule(v0, v1, v2, v3) => vec![v2, v3].into_iter(),
						Self::Copy(v0, v1, v2) => vec![v2].into_iter(),
						Self::Alloc(v0, v1, v2) => vec![].into_iter(),
						Self::Arg(v0, v1, v2, v3) => vec![].into_iter(),
						Self::Stkarg(v0, v1, v2, v3) => vec![].into_iter(),
						Self::Load(v0, v1, v2) => vec![v2].into_iter(),
						Self::Store(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Sext(v0, v1, v2) => vec![v2].into_iter(),
						Self::Zext(v0, v1, v2) => vec![v2].into_iter(),
						Self::Trunc(v0, v1, v2) => vec![v2].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0, v1) => vec![v1].into_iter(),
						Self::Br(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sub(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Umul(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Smul(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Udiv(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sdiv(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Eq(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sgt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sge(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Slt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Sle(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ugt(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Uge(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ult(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Ule(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Copy(v0, v1, v2) => vec![v1].into_iter(),
						Self::Alloc(v0, v1, v2) => vec![v1].into_iter(),
						Self::Arg(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Stkarg(v0, v1, v2, v3) => vec![v1].into_iter(),
						Self::Load(v0, v1, v2) => vec![v1].into_iter(),
						Self::Store(v0, v1, v2) => vec![].into_iter(),
						Self::Comment(v0) => vec![].into_iter(),
						Self::Sext(v0, v1, v2) => vec![v1].into_iter(),
						Self::Zext(v0, v1, v2) => vec![v1].into_iter(),
						Self::Trunc(v0, v1, v2) => vec![v1].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0, v1) => vec![].into_iter(),
						Self::Br(v0, v1, v2, v3) => vec![].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
						Self::Add(v0, v1, v2, v3) => false,
						Self::Sub(v0, v1, v2, v3) => false,
						Self::Umul(v0, v1, v2, v3) => false,
						Self::Smul(v0, v1, v2, v3) => false,
						Self::Udiv(v0, v1, v2, v3) => false,
						Self::Sdiv(v0, v1, v2, v3) => false,
						Self::Eq(v0, v1, v2, v3) => false,
						Self::Sgt(v0, v1, v2, v3) => false,
						Self::Sge(v0, v1, v2, v3) => false,
						Self::Slt(v0, v1, v2, v3) => false,
						Self::Sle(v0, v1, v2, v3) => false,
						Self::Ugt(v0, v1, v2, v3) => false,
						Self::Uge(v0, v1, v2, v3) => false,
						Self::Ult(v0, v1, v2, v3) => false,
						Self::Ule(v0, v1, v2, v3) => false,
						Self::Copy(v0, v1, v2) => false,
						Self::Alloc(v0, v1, v2) => false,
						Self::Arg(v0, v1, v2, v3) => false,
						Self::Stkarg(v0, v1, v2, v3) => false,
						Self::Load(v0, v1, v2) => false,
						Self::Store(v0, v1, v2) => false,
						Self::Comment(v0) => false,
						Self::Sext(v0, v1, v2) => false,
						Self::Zext(v0, v1, v2) => false,
						Self::Trunc(v0, v1, v2) => false,
						Self::Retv => true,
						Self::Ret(v0, v1) => true,
						Self::Br(v0, v1, v2, v3) => true,
						Self::Jmp(v0) => true
        }
    }

    fn uncond_jump(bb: BB) -> Self {
        Self::Jmp(bb)
    }
}
