
class InstrInfo:
    name: str
    fields: list[str]
    defs: list[str | int]
    uses: list[str | int]
    fmt: str
    is_terminator: bool

    def __init__(
        self,
        name: str,
        fields: list[str] = [],
        defs: list[str | int] = [],
        uses: list[str | int] = [],
        is_terminator: bool = False,
        fmt: str | None = None,
    ) -> None:
        self.name = name
        self.defs = defs
        self.uses = uses
        self.fields = fields
        self.is_terminator = is_terminator
        self.fmt = (
            fmt
            or (name + " " + ", ".join(f"{{v{i}}}" for i in range(len(fields)))).strip()
        )


class Arch:
    arch_name: str
    enum_name: str
    val_name: str
    instrs: list[InstrInfo]
    uncond_jump: InstrInfo

    def __init__(
        self,
        name: str,
        enum: str,
        val: str,
        instrs: list[InstrInfo],
        uncond_jump: InstrInfo,
    ):
        self.arch_name = name
        self.enum_name = enum
        self.val_name = val
        self.instrs = instrs
        self.uncond_jump = uncond_jump

    def gen_file(self) -> str:
        ret = f"""
#![allow(unused)]
///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/{self.arch_name}/instructions.py
///

use crate::common::*;
use crate::ast::*;
use crate::backend::*;
use crate::IRs::lir::*;

{self.gen_enum()}

{self.gen_display()}

{self.gen_trait()}
        """
        return ret.strip()

    def gen_enum(self) -> str:
        ret = "#[derive(Debug, Clone)]\n"
        ret += f"pub enum {self.enum_name} {{\n"
        for i in self.instrs:
            ret += f"\t\t{gen_enum_variant(i)},\n"
        ret += "}"
        return ret

    def gen_display(self) -> str:
        display_arms = ",\n".join(
            f"{gen_arm(i)} => {gen_display(i)}" for i in self.instrs
        )
        ret = f"""
impl std::fmt::Display for {self.enum_name} {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        match self {{
{display_arms}
        }}
    }}
}}
        """
        return ret

    def gen_trait(self) -> str:
        src_arms = ",\n".join(f"{gen_arm(i)} => {gen_srcs(i)}" for i in self.instrs)
        dst_arms = ",\n".join(f"{gen_arm(i)} => {gen_dsts(i)}" for i in self.instrs)
        term_arms = ",\n".join(f"{gen_arm(i)} => {str(i.is_terminator).lower()}" for i in self.instrs)
        ret = f"""
impl Instr for {self.enum_name} {{
    type Val = {self.val_name};

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {{
        match self {{
{src_arms}
        }}
    }}

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {{
        match self {{
{dst_arms}
        }}
    }}

    fn is_terminator(&self) -> bool {{
        match self {{
{term_arms}
        }}
    }}

    fn uncond_jump(bb: BBID) -> Self {{
        Self::{self.uncond_jump.name.capitalize()}(bb)
    }}
}}
        """
        return ret


def gen_display(instr: InstrInfo) -> str:
    return f'f.write_fmt(format_args!("{instr.fmt}"))'


def gen_arm(instr) -> str:
    inner = ", ".join(f"v{i}" for i in range(len(instr.fields)))
    params = "" if len(instr.fields) == 0 else f"({inner})"
    return f"\t\t\t\t\t\tSelf::{instr.name.capitalize()}{params}"


def gen_enum_variant(instr: InstrInfo) -> str:
    variant_name = instr.name.capitalize()
    field_names = ", ".join([f"{i}" for i in instr.fields])
    if len(instr.fields) > 0:
        return f"{variant_name}({field_names})"
    else:
        return f"{variant_name}"


def gen_srcs(instr: InstrInfo) -> str:
    vals = []
    for i in instr.uses:
        if type(i) == int:
            vals.append(f"v{i}")
        else:
            vals.append(i)
    vals = ", ".join(vals)
    return f"vec![{vals}].into_iter()"


def gen_dsts(instr: InstrInfo) -> str:
    vals = []
    for i in instr.defs:
        if type(i) == int:
            vals.append(f"v{i}")
        else:
            vals.append(i)
    vals = ", ".join(vals)
    return f"vec![{vals}].into_iter()"
