#![allow(unused)]
#![allow(nonstandard_style)]
// THIS FILE WAS AUTOGENERATED USING A SCRIPT.
// ANY CHANGES MADE HERE WILL BE LOST. 
// Please make changes to ./spec/x86MIR.pl instead.


// This file defines the ISA for x86MIR.


// Common imports needed by all ISAs:
use crate::traits::InstructionTrait;
use crate::builder::BBID;
use x86MIRInstr::*;

// Extra imports:
use super::*;

#[derive(Debug, Clone)]
pub enum x86MIRInstr {
    /// rs1, rs2
    Add(x86MIRValue, x86MIRValue),
    /// s
    Comment(String),
    /// dst, src
    Copy(x86MIRValue, x86MIRValue),
    /// dst
    Frameslot(x86MIRValue),
    /// rs1, rs2
    Idiv(x86MIRValue, x86MIRValue),
    /// rs1, rs2
    Imul(x86MIRValue, x86MIRValue),
    /// to, flag
    Jcc(BBID, x86MIRValue),
    /// to
    Jmp(BBID),
    /// dst, src
    Load(x86MIRValue, x86MIRValue),
    /// 
    Ret,
    /// dst, src
    Sext(x86MIRValue, x86MIRValue),
    /// dst, src
    Store(x86MIRValue, x86MIRValue),
    /// rs1, rs2
    Sub(x86MIRValue, x86MIRValue),
    /// dst, src
    Zext(x86MIRValue, x86MIRValue),
}

impl std::fmt::Display for x86MIRInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Add(rs1, rs2) => f.write_fmt(format_args!("add	 {rs1}, {rs2}")),
            Comment(s) => f.write_fmt(format_args!("; {s}")),
            Copy(dst, src) => f.write_fmt(format_args!("COPY	 {dst}, {src}")),
            Frameslot(dst) => f.write_fmt(format_args!("FSLOT	 {dst}")),
            Idiv(rs1, rs2) => f.write_fmt(format_args!("idiv	 {rs1}, {rs2}")),
            Imul(rs1, rs2) => f.write_fmt(format_args!("imul	 {rs1}, {rs2}")),
            Jcc(to, flag) => f.write_fmt(format_args!("JCC	 {to}, {flag}")),
            Jmp(to) => f.write_fmt(format_args!("jmp {to}")),
            Load(dst, src) => f.write_fmt(format_args!("LOAD	 {dst}, {src}")),
            Ret => f.write_fmt(format_args!("ret	")),
            Sext(dst, src) => f.write_fmt(format_args!("movsx	 {dst}, {src}")),
            Store(dst, src) => f.write_fmt(format_args!("STORE	 {dst}, {src}")),
            Sub(rs1, rs2) => f.write_fmt(format_args!("sub	 {rs1}, {rs2}")),
            Zext(dst, src) => f.write_fmt(format_args!("movzx	 {dst}, {src}")),
        }
    }
}

impl InstructionTrait for x86MIRInstr {
    type Val = x86MIRValue;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Comment(s) => vec![].into_iter(),
            Copy(dst, src) => vec![src].into_iter(),
            Frameslot(dst) => vec![].into_iter(),
            Idiv(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Imul(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Jcc(to, flag) => vec![flag].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Load(dst, src) => vec![src].into_iter(),
            Ret => vec![].into_iter(),
            Sext(dst, src) => vec![src].into_iter(),
            Store(dst, src) => vec![src].into_iter(),
            Sub(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Zext(dst, src) => vec![src].into_iter(),
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1].into_iter(),
            Comment(s) => vec![].into_iter(),
            Copy(dst, src) => vec![dst].into_iter(),
            Frameslot(dst) => vec![dst].into_iter(),
            Idiv(rs1, rs2) => vec![rs1].into_iter(),
            Imul(rs1, rs2) => vec![rs1].into_iter(),
            Jcc(to, flag) => vec![].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Load(dst, src) => vec![dst].into_iter(),
            Ret => vec![].into_iter(),
            Sext(dst, src) => vec![dst].into_iter(),
            Store(dst, src) => vec![dst].into_iter(),
            Sub(rs1, rs2) => vec![rs1].into_iter(),
            Zext(dst, src) => vec![dst].into_iter(),
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
            Add(rs1, rs2) => false,
            Comment(s) => false,
            Copy(dst, src) => false,
            Frameslot(dst) => false,
            Idiv(rs1, rs2) => false,
            Imul(rs1, rs2) => false,
            Jcc(to, flag) => true,
            Jmp(to) => true,
            Load(dst, src) => false,
            Ret => true,
            Sext(dst, src) => false,
            Store(dst, src) => false,
            Sub(rs1, rs2) => false,
            Zext(dst, src) => false,
        }
    }
}

