#![allow(unused)]
#![allow(nonstandard_style)]
// THIS FILE WAS AUTOGENERATED USING A SCRIPT.
// Any changes made here can be lost! Please view ./spec/x86.pl to make changes.


// This file defines the ISA for x86.


// Common imports needed by all ISAs:
use crate::traits::InstructionTrait;
use crate::builder::BBID;
use x86Instr::*;

// Extra imports:
use super::*;

#[derive(Debug, Clone)]
pub enum x86Instr {
    Add(x86Val, x86Val),
    Cmove(x86Val, x86Val),
    Cmovg(x86Val, x86Val),
    Cmovge(x86Val, x86Val),
    Cmovl(x86Val, x86Val),
    Cmovle(x86Val, x86Val),
    Cmovne(x86Val, x86Val),
    Comment(String),
    Idiv(x86Val, x86Val),
    Imul(x86Val, x86Val),
    Je(BBID),
    Jg(BBID),
    Jge(BBID),
    Jl(BBID),
    Jle(BBID),
    Jmp(BBID),
    Jne(BBID),
    Jno(BBID),
    Jnz(BBID),
    Jo(BBID),
    Jz(BBID),
    Lea(x86Val, x86Val),
    Mov(x86Val, x86Val),
    Movsx(x86Val, x86Val),
    Movsxd(x86Val, x86Val),
    Movzx(x86Val, x86Val),
    Pop(x86Val),
    Push(x86Val),
    Ret,
    Sub(x86Val, x86Val),
}

impl std::fmt::Display for x86Instr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Add(rs1, rs2) => f.write_fmt(format_args!("add {rs1}, {rs2}")),
            Cmove(dst, rs1) => f.write_fmt(format_args!("cmove {dst}, {rs1}")),
            Cmovg(dst, rs1) => f.write_fmt(format_args!("cmovg {dst}, {rs1}")),
            Cmovge(dst, rs1) => f.write_fmt(format_args!("cmovge {dst}, {rs1}")),
            Cmovl(dst, rs1) => f.write_fmt(format_args!("cmovl {dst}, {rs1}")),
            Cmovle(dst, rs1) => f.write_fmt(format_args!("cmovle {dst}, {rs1}")),
            Cmovne(dst, rs1) => f.write_fmt(format_args!("cmovne {dst}, {rs1}")),
            Comment(s) => f.write_fmt(format_args!("; {s}")),
            Idiv(rs1, rs2) => f.write_fmt(format_args!("idiv {rs1}, {rs2}")),
            Imul(rs1, rs2) => f.write_fmt(format_args!("imul {rs1}, {rs2}")),
            Je(to) => f.write_fmt(format_args!("je {to}")),
            Jg(to) => f.write_fmt(format_args!("jg {to}")),
            Jge(to) => f.write_fmt(format_args!("jge {to}")),
            Jl(to) => f.write_fmt(format_args!("jl {to}")),
            Jle(to) => f.write_fmt(format_args!("jle {to}")),
            Jmp(to) => f.write_fmt(format_args!("jmp {to}")),
            Jne(to) => f.write_fmt(format_args!("jne {to}")),
            Jno(to) => f.write_fmt(format_args!("jno {to}")),
            Jnz(to) => f.write_fmt(format_args!("jnz {to}")),
            Jo(to) => f.write_fmt(format_args!("jo {to}")),
            Jz(to) => f.write_fmt(format_args!("jz {to}")),
            Lea(dst, rs1) => f.write_fmt(format_args!("lea {dst}, {rs1}")),
            Mov(dst, rs1) => f.write_fmt(format_args!("mov {dst}, {rs1}")),
            Movsx(dst, rs1) => f.write_fmt(format_args!("movsx {dst}, {rs1}")),
            Movsxd(dst, rs1) => f.write_fmt(format_args!("movsxd {dst}, {rs1}")),
            Movzx(dst, rs1) => f.write_fmt(format_args!("movzx {dst}, {rs1}")),
            Pop(dst) => f.write_fmt(format_args!("pop {dst}")),
            Push(rs1) => f.write_fmt(format_args!("push {rs1}")),
            Ret => f.write_fmt(format_args!("ret")),
            Sub(rs1, rs2) => f.write_fmt(format_args!("sub {rs1}, {rs2}")),
        }
    }
}

impl InstructionTrait for x86Instr {
    type Val = x86Val;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Cmove(dst, rs1) => vec![rs1].into_iter(),
            Cmovg(dst, rs1) => vec![rs1].into_iter(),
            Cmovge(dst, rs1) => vec![rs1].into_iter(),
            Cmovl(dst, rs1) => vec![rs1].into_iter(),
            Cmovle(dst, rs1) => vec![rs1].into_iter(),
            Cmovne(dst, rs1) => vec![rs1].into_iter(),
            Comment(s) => vec![].into_iter(),
            Idiv(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Imul(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Je(to) => vec![].into_iter(),
            Jg(to) => vec![].into_iter(),
            Jge(to) => vec![].into_iter(),
            Jl(to) => vec![].into_iter(),
            Jle(to) => vec![].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Jne(to) => vec![].into_iter(),
            Jno(to) => vec![].into_iter(),
            Jnz(to) => vec![].into_iter(),
            Jo(to) => vec![].into_iter(),
            Jz(to) => vec![].into_iter(),
            Lea(dst, rs1) => vec![rs1].into_iter(),
            Mov(dst, rs1) => vec![rs1].into_iter(),
            Movsx(dst, rs1) => vec![rs1].into_iter(),
            Movsxd(dst, rs1) => vec![rs1].into_iter(),
            Movzx(dst, rs1) => vec![rs1].into_iter(),
            Pop(dst) => vec![].into_iter(),
            Push(rs1) => vec![{rs1}].into_iter(),
            Ret => vec![].into_iter(),
            Sub(rs1, rs2) => vec![rs1, rs2].into_iter(),
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
            Add(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Cmove(dst, rs1) => vec![rs1].into_iter(),
            Cmovg(dst, rs1) => vec![rs1].into_iter(),
            Cmovge(dst, rs1) => vec![rs1].into_iter(),
            Cmovl(dst, rs1) => vec![rs1].into_iter(),
            Cmovle(dst, rs1) => vec![rs1].into_iter(),
            Cmovne(dst, rs1) => vec![rs1].into_iter(),
            Comment(s) => vec![].into_iter(),
            Idiv(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Imul(rs1, rs2) => vec![rs1, rs2].into_iter(),
            Je(to) => vec![].into_iter(),
            Jg(to) => vec![].into_iter(),
            Jge(to) => vec![].into_iter(),
            Jl(to) => vec![].into_iter(),
            Jle(to) => vec![].into_iter(),
            Jmp(to) => vec![].into_iter(),
            Jne(to) => vec![].into_iter(),
            Jno(to) => vec![].into_iter(),
            Jnz(to) => vec![].into_iter(),
            Jo(to) => vec![].into_iter(),
            Jz(to) => vec![].into_iter(),
            Lea(dst, rs1) => vec![rs1].into_iter(),
            Mov(dst, rs1) => vec![rs1].into_iter(),
            Movsx(dst, rs1) => vec![rs1].into_iter(),
            Movsxd(dst, rs1) => vec![rs1].into_iter(),
            Movzx(dst, rs1) => vec![rs1].into_iter(),
            Pop(dst) => vec![].into_iter(),
            Push(rs1) => vec![{rs1}].into_iter(),
            Ret => vec![].into_iter(),
            Sub(rs1, rs2) => vec![rs1, rs2].into_iter(),
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
            Add(rs1, rs2) => false,
            Cmove(dst, rs1) => false,
            Cmovg(dst, rs1) => false,
            Cmovge(dst, rs1) => false,
            Cmovl(dst, rs1) => false,
            Cmovle(dst, rs1) => false,
            Cmovne(dst, rs1) => false,
            Comment(s) => false,
            Idiv(rs1, rs2) => false,
            Imul(rs1, rs2) => false,
            Je(to) => true,
            Jg(to) => true,
            Jge(to) => true,
            Jl(to) => true,
            Jle(to) => true,
            Jmp(to) => true,
            Jne(to) => true,
            Jno(to) => true,
            Jnz(to) => true,
            Jo(to) => true,
            Jz(to) => true,
            Lea(dst, rs1) => false,
            Mov(dst, rs1) => false,
            Movsx(dst, rs1) => false,
            Movsxd(dst, rs1) => false,
            Movzx(dst, rs1) => false,
            Pop(dst) => false,
            Push(rs1) => false,
            Ret => true,
            Sub(rs1, rs2) => false,
        }
    }
}

