///
/// THIS FILE WAS AUTOGENERATED WITH A PYTHON SCRIPT.
///
/// To view and/or make changes to the contents of this file,
/// see compiler/src/autogen/lir/instructions.py
///

use crate::prelude::*;
use crate::arch::lir::*;

#[derive(Debug, Clone)]
pub enum LirInstr {
		Add(LirVal, LirVal, LirVal),
		Sub(LirVal, LirVal, LirVal),
		Umul(LirVal, LirVal, LirVal),
		Smul(LirVal, LirVal, LirVal),
		Udiv(LirVal, LirVal, LirVal),
		Sdiv(LirVal, LirVal, LirVal),
		Eq(LirVal, LirVal, LirVal),
		Sgt(LirVal, LirVal, LirVal),
		Sge(LirVal, LirVal, LirVal),
		Slt(LirVal, LirVal, LirVal),
		Sle(LirVal, LirVal, LirVal),
		Ugt(LirVal, LirVal, LirVal),
		Uge(LirVal, LirVal, LirVal),
		Ult(LirVal, LirVal, LirVal),
		Ule(LirVal, LirVal, LirVal),
		Copy(LirVal, LirVal),
		Alloc(LirVal, StringId),
		Param(LirVal, StringId, usize),
		Load(LirVal, LirVal),
		Store(LirVal, LirVal),
		Retv,
		Ret(LirVal),
		Br(LirVal, BB, BB),
		Jmp(BB),
}


impl std::fmt::Display for LirInstr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
						Self::Add(v0, v1, v2) => f.write_fmt(format_args!("add {v0}, {v1}, {v2}")),
						Self::Sub(v0, v1, v2) => f.write_fmt(format_args!("sub {v0}, {v1}, {v2}")),
						Self::Umul(v0, v1, v2) => f.write_fmt(format_args!("umul {v0}, {v1}, {v2}")),
						Self::Smul(v0, v1, v2) => f.write_fmt(format_args!("smul {v0}, {v1}, {v2}")),
						Self::Udiv(v0, v1, v2) => f.write_fmt(format_args!("udiv {v0}, {v1}, {v2}")),
						Self::Sdiv(v0, v1, v2) => f.write_fmt(format_args!("sdiv {v0}, {v1}, {v2}")),
						Self::Eq(v0, v1, v2) => f.write_fmt(format_args!("eq {v0}, {v1}, {v2}")),
						Self::Sgt(v0, v1, v2) => f.write_fmt(format_args!("sgt {v0}, {v1}, {v2}")),
						Self::Sge(v0, v1, v2) => f.write_fmt(format_args!("sge {v0}, {v1}, {v2}")),
						Self::Slt(v0, v1, v2) => f.write_fmt(format_args!("slt {v0}, {v1}, {v2}")),
						Self::Sle(v0, v1, v2) => f.write_fmt(format_args!("sle {v0}, {v1}, {v2}")),
						Self::Ugt(v0, v1, v2) => f.write_fmt(format_args!("ugt {v0}, {v1}, {v2}")),
						Self::Uge(v0, v1, v2) => f.write_fmt(format_args!("uge {v0}, {v1}, {v2}")),
						Self::Ult(v0, v1, v2) => f.write_fmt(format_args!("ult {v0}, {v1}, {v2}")),
						Self::Ule(v0, v1, v2) => f.write_fmt(format_args!("ule {v0}, {v1}, {v2}")),
						Self::Copy(v0, v1) => f.write_fmt(format_args!("copy {v0}, {v1}")),
						Self::Alloc(v0, v1) => f.write_fmt(format_args!("alloc {v0}, {v1}")),
						Self::Param(v0, v1, v2) => f.write_fmt(format_args!("param {v0}, {v1}, {v2}")),
						Self::Load(v0, v1) => f.write_fmt(format_args!("load {v0}, {v1}")),
						Self::Store(v0, v1) => f.write_fmt(format_args!("store {v0}, {v1}")),
						Self::Retv => f.write_fmt(format_args!("retv")),
						Self::Ret(v0) => f.write_fmt(format_args!("ret {v0}")),
						Self::Br(v0, v1, v2) => f.write_fmt(format_args!("br {v0}, {v1}, {v2}")),
						Self::Jmp(v0) => f.write_fmt(format_args!("jmp {v0}"))
        }
    }
}
        


impl Instr for LirInstr {
    type Val = LirVal;

    fn srcs(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Sub(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Umul(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Smul(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Udiv(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Sdiv(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Eq(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Sgt(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Sge(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Slt(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Sle(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Ugt(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Uge(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Ult(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Ule(v0, v1, v2) => vec![v1, v2].into_iter(),
						Self::Copy(v0, v1) => vec![v1].into_iter(),
						Self::Alloc(v0, v1) => vec![].into_iter(),
						Self::Param(v0, v1, v2) => vec![].into_iter(),
						Self::Load(v0, v1) => vec![v1].into_iter(),
						Self::Store(v0, v1) => vec![v0, v1].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0) => vec![v0].into_iter(),
						Self::Br(v0, v1, v2) => vec![v0].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn dsts(&mut self) -> impl Iterator<Item = &mut Self::Val> {
        match self {
						Self::Add(v0, v1, v2) => vec![v0].into_iter(),
						Self::Sub(v0, v1, v2) => vec![v0].into_iter(),
						Self::Umul(v0, v1, v2) => vec![v0].into_iter(),
						Self::Smul(v0, v1, v2) => vec![v0].into_iter(),
						Self::Udiv(v0, v1, v2) => vec![v0].into_iter(),
						Self::Sdiv(v0, v1, v2) => vec![v0].into_iter(),
						Self::Eq(v0, v1, v2) => vec![v0].into_iter(),
						Self::Sgt(v0, v1, v2) => vec![v0].into_iter(),
						Self::Sge(v0, v1, v2) => vec![v0].into_iter(),
						Self::Slt(v0, v1, v2) => vec![v0].into_iter(),
						Self::Sle(v0, v1, v2) => vec![v0].into_iter(),
						Self::Ugt(v0, v1, v2) => vec![v0].into_iter(),
						Self::Uge(v0, v1, v2) => vec![v0].into_iter(),
						Self::Ult(v0, v1, v2) => vec![v0].into_iter(),
						Self::Ule(v0, v1, v2) => vec![v0].into_iter(),
						Self::Copy(v0, v1) => vec![v0].into_iter(),
						Self::Alloc(v0, v1) => vec![v0].into_iter(),
						Self::Param(v0, v1, v2) => vec![v0].into_iter(),
						Self::Load(v0, v1) => vec![v0].into_iter(),
						Self::Store(v0, v1) => vec![].into_iter(),
						Self::Retv => vec![].into_iter(),
						Self::Ret(v0) => vec![].into_iter(),
						Self::Br(v0, v1, v2) => vec![].into_iter(),
						Self::Jmp(v0) => vec![].into_iter()
        }
    }

    fn is_terminator(&self) -> bool {
        match self {
						Self::Add(v0, v1, v2) => false,
						Self::Sub(v0, v1, v2) => false,
						Self::Umul(v0, v1, v2) => false,
						Self::Smul(v0, v1, v2) => false,
						Self::Udiv(v0, v1, v2) => false,
						Self::Sdiv(v0, v1, v2) => false,
						Self::Eq(v0, v1, v2) => false,
						Self::Sgt(v0, v1, v2) => false,
						Self::Sge(v0, v1, v2) => false,
						Self::Slt(v0, v1, v2) => false,
						Self::Sle(v0, v1, v2) => false,
						Self::Ugt(v0, v1, v2) => false,
						Self::Uge(v0, v1, v2) => false,
						Self::Ult(v0, v1, v2) => false,
						Self::Ule(v0, v1, v2) => false,
						Self::Copy(v0, v1) => false,
						Self::Alloc(v0, v1) => false,
						Self::Param(v0, v1, v2) => false,
						Self::Load(v0, v1) => false,
						Self::Store(v0, v1) => false,
						Self::Retv => true,
						Self::Ret(v0) => true,
						Self::Br(v0, v1, v2) => true,
						Self::Jmp(v0) => true
        }
    }

    fn uncond_jump(bb: BB) -> Self {
        Self::Jmp(bb)
    }
}
